### ISSUE TITLE
Would love to use this service...

### ISSUE THREAD

**Issue by sirvon** [Ziggeo/ZiggeoAndroidSDK#1]
I would love to use ziggeo in my app, but quite frankly there isn't enough directory to
be in play.

Can you give us something more to work with, in terms of acting implementing the lib in a functioning app.

Specifically, when a user records a video, How can I then play that video back
where do i get the url of the previously recorded video?

thanks for your work!

**Comment by gdimaggio** [comment]
Hey sirvon,

The readme file just explains how to instantiate the recorder and player on their own,
while in some cases you want to go from the former to the latter, i.e. displaying a video 
which has just been recorded.

In order to do that, I suggest you declare the recorder fragment as a global variable, 
then make use of OnUploadCompletedCallback to be notified when a recorded video
has been uploaded, so that you can instantiate a player to play it back:

``` java
videoRecorderFragment.callback = new OnUploadCompletedCallback() {
        public void OnUploadCompleted(String videoToken, String imagePath) {
            // Instatiate player with videoToken
        }
        public void OnVideoRerecord() { ... }
}; 
```

If you have any more questions just ask :)
